### ISSUE TITLE
THE BEST GRAFT PROGRAM EVER!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by Raory** [andybalaam/graft#1]
![299treadmill](https://user-images.githubusercontent.com/18234409/39097080-736ca4f6-464f-11e8-8431-a98051b9d9e4.gif)
                      ^
  this is really cool, I call it the 'treadmill299' ples like dis :grin:

```   ./graft '180=d8:S90=d:J0=d8:J' --lookahead-steps=10 --gif=299treadmill.gif --frames=1000```

**Comment by Raory** [comment]
#like dis

**Comment by andybalaam** [comment]
This is awesome!
